### ISSUE TITLE
Why in hello-syncsignal project the OrderWorkflow2 class is derived from IOrderWorkflow1 and stab2 using IOrderWorkflow1 interface?

### ISSUE THREAD

**Issue by Yuriy-Paramonov** [nforgeio/cadence-samples#2]

**Comment by jefflill** [comment]
I'll bet that was a copy-paste thing where I duplicated `OrderWorkflow2` from `OrderWorkflow1` and didn't rename the parent interface.  This happened to work because the interfaces define the same methods.

We'll do a better QC pass before releasing the Temporal based client.

**FYI:** We're not spending much time on the Cadence right now and going forward.  We're in the middle of porting to Temporal which I expect will be the long-term supported solution.

**Comment by jefflill** [comment]
Thanks again!  I've made this change and also corrected a bit of grammar in a comment.

**Comment by Yuriy-Paramonov** [comment]
Hello Jeff,

Do you really intend to create stub1 (line 368) and stub2 (line 383) of the Program.cs file using IOrderWorkflow1 interface for both of them? Please let me know if there is any sense to look at these samples (event they looks like released) before Temporal project will be implemented. The reason why I am asking is the strange behavior observed with multiple calls to CancelAsync of the OrderWorkflow1 type. Even when I change stub2 to use IOrderWorkflow2 interface.

Best regards,
Yuriy

**Comment by jefflill** [comment]
I'll take a look.

**Comment by Yuriy-Paramonov** [comment]
Thanks Jeff:)

**Comment by jefflill** [comment]
Sorry it took so long to get back to this, I've been deep into a couple other projects.

So I changed interface type for `stub2` to `IOrderWorkflow2` and set a breakpoint just after where we write the results to the console.  Both printed as **false** as expected.  **What were you seeing?**

Note that this sample is a bit contrived because the workflows are sleeping 5 seconds to give the program a chance to cancel them.  The `Workflow.SleepAsync(TimeSpan.FromSeconds(5))` calls are actually processed by the Cadence server so this is not like `Thread.Sleep()` or `Task.Delay()` which is executed within the local process.

I suspect that at some point you may have stopped in the debugger at a breakpoint after the workflows were started but before they were cancelled.  If the debugger had the program stopped for 5 or more seconds, when it continues Cadence will immediately continue execution after the sleep calls and we'd see a race condition for the synchronous signal to be received or for the workflows to complete successfully,

The synchronous signal implementation experimental is a bit of a hack and I suspect that in this case, the signal will lose the race most of the time, but the winner could still be somewhat random.

I spoke with Maxim at http://temporal.io several months ago and he has a better idea for integrating something this into Temporal but they've been busy getting their first release out.
